### ISSUE TITLE
Sm4sh crashes with IPS files

### ISSUE THREAD

**Issue by daemonspudguy** [Swiftloke/ModMoon#11]
The dump is in the archive
[crash_dump_00000003.zip](https://github.com/Swiftloke/ModMoon/files/3080154/crash_dump_00000003.zip)

**Comment by Swiftloke** [comment]
This is not a support forum, and furthermore this is not a problem with ModMoon but with either SaltySD or the modpack(s) in question. See #7. If you seek assistance, there are plenty of places, such as Nintendo Homebrew or our own USM-eM Discord server, that will be able to help you.
