### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by mtheall** [Swiftloke/ModMoon#2]
https://github.com/Swiftloke/ModMoon/blob/2d9258a56b16cd8aa2ea9966d09db159196d0e23/source/initialsetup.cpp#L187

error: 'controlsmodifierbutton' was not declared in this scope

**Comment by Dannyo15** [comment]
Hello, he told someone else that he hasn't committed a change yet. He said earlier to change it to "activetitlesbutton" and it should work.

**Comment by Swiftloke** [comment]
Change with some new buttons caused this to slip through the cracks of commits. Fixed with https://github.com/Swiftloke/ModMoon/commit/6b14c16a8f032a0364c0e42c286961f5c567ede8.
