### ISSUE TITLE
Pinpointed cause of crash

### ISSUE THREAD

**Issue by mtheall** [Swiftloke/ModMoon#4]
https://github.com/Swiftloke/ModMoon/blob/922dc9108e7b6b5a8b9188b8adb0484f4e28d4bf/source/smdh.cpp#L98

The +1 causes this to go out-of-bounds:
https://github.com/Swiftloke/ModMoon/blob/922dc9108e7b6b5a8b9188b8adb0484f4e28d4bf/source/smdh.cpp#L99

This is the source of the crashes we've been debugging.

**Comment by Swiftloke** [comment]
I owe you big time for this. Taken care of with this commit: https://github.com/Swiftloke/ModMoon/commit/6a822b83cef608fba4bc7bbdf0ea1983f9fbaa30
