### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by CollinScripter** [Swiftloke/ModMoon#8]
I was not able to find a License in ModMoon's repo. This means that users have [no permission from the creators of the software to use, modify, or share the software.](https://choosealicense.com/no-permission/) If you could, please [choose an open source license](https://choosealicense.com/) to allow for modification.

**Comment by Swiftloke** [comment]
Hey, I put this off until someone started calling me out on it because I was too lazy to commit to something. Give me a day or two and I'll pick one. Thanks for giving me a shove :)

**Comment by CollinScripter** [comment]
To be honest, I would've done the same thing. I'm planning on forking it
(mostly because of the fancy UI) for my own homebrew, so it was needed

**Comment by Swiftloke** [comment]
What code do you intend on using? The engine is going through a lot of revamp right now, and for the most part I discourage its usage by other people in favor of citro2d. sDraw is (or will be) a powerful engine, BUT you really need graphics programming knowledge to use it.

**Comment by CollinScripter** [comment]
May have to make my own UI with citro2d then, as I haven't done much with graphics. I'll still probably borrow some stuff though, such as the updater. ¯\_(ツ)_/¯

**Comment by Swiftloke** [comment]
Sorry for leaving this alone. Licensing is important. GPLv3 with sections 7.b and 7.c align with my interests, and ModMoon is now licensed under it.
